# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-12 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(default='cool'),
            preserve_default=False,
        ),
    ]
