# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-15 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quoted_by',
            field=models.CharField(default='Nelson Mandela', max_length=45),
            preserve_default=False,
        ),
    ]
